"""aluno

Revision ID: 476cc9e19d7f
Revises: 
Create Date: 2023-06-12 18:34:03.181770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476cc9e19d7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('av1', sa.Float(), nullable=False),
    sa.Column('av2', sa.Float(), nullable=False),
    sa.Column('media', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('cpf'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('professor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('materia', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professor')
    op.drop_table('aluno')
    # ### end Alembic commands ###
